pull_request_rules:
    - name: Automatic merge on approval
      conditions:
        - "label=automerge"
        - "#approved-reviews-by>=1"
        - "status-success=Code lint check"
      actions:
        merge:
          method: squash

    - name: Ask to resolve conflict
      conditions:
        - conflict
      actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it? ğŸ™
