pull_request_rules:
    - name: Automatic merge on approval after CI passed
      conditions:
        - "label=PR | automerge"
        - "label=PR | trigger CI"
        - "#approved-reviews-by>=1"
        - "status-success=Code lint check"
        - "status-success=CI ubuntu-18.04"
        - "status-success=CI ubuntu-20.04"
      actions:
        merge:
          method: squash

    - name: Automatic merge on approval
      conditions:
        - "label=PR | automerge"
        - "label=PR | ignore CI"
        - "#approved-reviews-by>=1"
        - "status-success=Code lint check"
      actions:
        merge:
          method: squash

    - name: Ask to resolve conflict
      conditions:
        - conflict
      actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it? ğŸ™
