name: Check proto on pull request

on:
  pull_request:
    branches:
      - 2.3

jobs:
  build:
    name: Run Check Proto
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.12]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Fetch tags
      run: |
        git fetch --prune --unshallow --tags

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Try generate proto
      run: |
        git submodule update --init
        make check_proto_product

