name: Unit Test CI

# Run this workflow every time a new commit pushed to master repository
on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-18.04
#    if: startsWith(github.event.head_commit.message, '[ci]')
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        env:
          message: ${{ github.event.head_commit.message }}
        with:
          path: pymilvus
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install -r pymilvus/requirements.txt
          echo ${{ toJson(github.event) }}
          echo ${{ startsWith(github.event.head_commit.message, '[ci]') }}
      - name: Run server docker
        # Ignore the failure of a step and avoid terminating the job.
        run: |
          cd pymilvus/.github/scripts/server
          docker-compose -f server.yml up -d
          cd -
      - name: Run unit test
        run: |
          cd pymilvus
          python -m pytest
      - name: Clean server docker
        run: |
          cd pymilvus/.github/scripts/server
          docker-compose -f server.yml down
          cd -

