name: Unit Test CI

# Run this workflow every time a new commit pushed to master repository
on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-18.04
#    if: "contains(github.event.head_commit.message, 'ci')"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: pymilvus
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install -r pymilvus/requirements.txt
      - name: Run server docker
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        run: |
          cd pymilvus/.github/scripts/server
          docker-compose -f all_in_one.yml up -d
          cd -
      - name: Run unit test
        continue-on-error: true
        shell: python
        run: |
          pytest
      - name: Clean server docker
        run: |
          cd pymilvus/.github/scripts/server
          docker-compose -f all_in_one.yml down
          cd -

