name: Unit Test CI

# Run this workflow every time a new commit pushed to master repository
on: pull_request

jobs:
  check:
    name: Check Head Commit
    runs-on: ubuntu-18.04
    outputs:
      status: ${{ steps.ci.outputs.test }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: |
          sudo apt-get update
          sudo apt install git tig
      - id: ci
        name: Read head commit
        run: |
          message = "$(git show-branch --no-name HEAD)"
          echo "$message"
          cis = "[ci]"
          if [[ "$message" == $cis.* ]]; then
            echo "::set-output name=test::yes"
          else
            echo "::set-output name=test::no"
          fi
  ci:
    name: CI
    runs-on: ubuntu-18.04
    needs: check
    if: needs.check.outputs.status == 'yes'
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: pymilvus
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          pip install -r pymilvus/requirements.txt
          cd pymilvus
          echo ${{ github.event.after }}
      - name: Run server docker
        run: |
          cd pymilvus/.github/scripts/server
          docker-compose -f server.yml up -d
          cd -
      - name: Run unit test
        run: |
          cd pymilvus
          python -m pytest
      - name: Clean server docker
        run: |
          cd pymilvus/.github/scripts/server
          docker-compose -f server.yml down
          cd -

