name: Code checker on pull request

on:
  pull_request:
    branches:
      - 2.6

jobs:
  code-lint:
    name: Code lint check
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8, 3.13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check pyproject.toml install
        run: |
          pip install -e .
      - name: Install requirements
        run: |
          pip install -e ".[dev]"
      - name: Run pylint
        shell: bash
        run: |
          make lint
