name: Html-Publish

# Run this workflow every time a new commit pushed to master repository
on:
  pull_request:
    branches:
      - master
    paths:
      - 'milvus/client/stub.py'
      - 'doc/**'

jobs:
  html-publish:
    name: Publish html base
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: pymilvus
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install -r pymilvus/requirements.txt
      - name: Extract sdk version
        shell: python
        run: |
          import sys
          sys.path.append("./pymilvus")
          import milvus
          version = milvus.__version__
          print(f"pymilvus version is {version}")
      - name: Make html
        working-directory: pymilvus/doc
        run: |
          make html
          echo 'Make html successfully'
